services:
  - type: web
    name: agente
    env: python
    buildCommand: |
      python3 -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python3 agente.py
    plan: free
